#pragma once

// enum DIRECTION {DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_END};
enum OBJ_ID {OBJ_PLAYER, OBJ_MONSTER, OBJ_BOSSMONSTER, OBJ_SPONER, OBJ_BULLET, OBJ_BOSSMONSTERBULLET, OBJ_END};

enum SCENE {NONE, START, PLAYE, CLEAR};